export default {
  content: ["./index.html","./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#3525cd",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        secondary: "#565e74",
        "secondary-container": "#dae2fd",
        "secondary-fixed": "#dae2fd",
        tertiary: "#7e3000",
        "tertiary-fixed": "#ffdbcc",
        background: "#fcf8ff",
        surface: "#fcf8ff",
        "surface-bright": "#fcf8ff",
        "surface-dim": "#dcd8e5",
        "surface-variant": "#e4e1ee",
        "surface-container": "#f0ecf9",
        "surface-container-low": "#f5f2ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae6f4",
        "surface-container-highest": "#e4e1ee",
        "on-surface": "#1b1b24",
        "on-surface-variant": "#464555",
        outline: "#777587",
        "outline-variant": "#c7c4d8",
        error: "#ba1a1a",
        "inverse-surface": "#302f39",
        "inverse-primary": "#c3c0ff",
      },
      fontFamily: { sans: ["Inter", "system-ui", "sans-serif"] },
      fontSize: {
        "display": ["44px", { lineHeight: "48px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-xl": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "24px" }],
        "body-md": ["15px", { lineHeight: "22px" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
